services:
  diamondplanner:
    restart: unless-stopped
    environment:
      BSM_API_URL: ${BSM_API_URL}
      BSM_API_HOST: ${BSM_API_HOST}
      PUBLIC_TYPO3_URL: ${PUBLIC_TYPO3_URL}
      APPLICATION_CONTEXT: ${APPLICATION_CONTEXT}
      APPLICATION_SECRET: ${APPLICATION_SECRET}
      TIME_ZONE: ${TIME_ZONE}
      BSM_API_KEY: ${BSM_API_KEY}
      PLAYER_CHANGE_WEBHOOK_IDENTIFIER: ${PLAYER_CHANGE_WEBHOOK_IDENTIFIER}
      PLAYER_CHANGE_WEBHOOK_SECRET: ${PLAYER_CHANGE_WEBHOOK_SECRET}
      PLAYER_UPDATE_REACTION_IDENTIFIER: ${PLAYER_UPDATE_REACTION_IDENTIFIER}
      PLAYER_UPDATE_REACTION_SECRET: ${PLAYER_UPDATE_REACTION_SECRET}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBSCRIBER: ${VAPID_SUBSCRIBER}
    networks:
      - proxy
    volumes:
      - pb_data:/app/pb_data
