### authentication to Pocketbase with password
POST http://127.0.0.1:8090/api/collections/users/auth-with-password
Content-Type: application/json

{
  "identity": "karltestmichel@example.com",
  "password": "{{userPassword}}"
}

### creating a new user - invalid key
POST http://127.0.0.1:8090/api/collections/users/records
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "{{userPassword}}",
  "signup_key": "INVALID_NON_EXISTENT"
}

### creating a new user - valid key
POST http://127.0.0.1:8090/api/collections/users/records
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "{{userPassword}}",
  "signup_key": "{{validSignupKey}}"
}