### authentication to Pocketbase with password
POST http://127.0.0.1:8090/api/collections/users/auth-with-password
Content-Type: application/json

{
  "identity": "karltestmichel@example.com",
  "password": "{{userPassword}}"
}

###