### authentication to Pocketbase with password
POST {{pbURL}}/api/collections/users/auth-with-password
Content-Type: application/json

{
  "identity": "karltestmichel@example.com",
  "password": "{{userPassword}}"
}

### creating a new user - invalid key
POST {{pbURL}}/api/collections/users/records
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "{{userPassword}}",
  "passwordConfirm": "{{userPassword}}",
  "signup_key": "INVALID_NON_EXISTENT"
}

### creating a new user - valid key
POST {{pbURL}}/api/collections/users/records
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "{{userPassword}}",
  "passwordConfirm": "{{userPassword}}",
  "signup_key": "{{validSignupKey}}"
}