name: Deploy Staging (Docker)

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
    branches:
      - stage
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      environment: Staging
      branch: 'stage'
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}